### PR TITLE
Minor update to RFtools and DeepResonance

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by 3TUSK** [comment]
Call @GWYOG, also try calling @Glease

> I go to the Finals

**Comment by 3TUSK** [comment]
@Glease check out #65

**Comment by Glease** [comment]
@3TUSK
 Well, I'd love to help, 但我高三，快高考了，虽然没有大问题但是父母很关心，没办法花大量的时间去翻译，也就能聊聊天看看小说(我甚至停掉了开发)，所以…… Sorry for that. 也许考完可以来帮帮忙，暂时是不行了。

@partial-s
IIRC, rftools and deepresonance both have its own translation. rftools's need an minor update of one single entry, but your patch lacks more than additions. (the latest official zh_CN.lang for rftools has 200+ lines, but yours has only ~150 lines) Meanwhile, deepresonance has everything ready. nothing really needs changes.  (both of above two happens months ago!) There must be something wrong. Did you referenced some ancient en_US.lang files?

--- Original Message ---

**Comment by ghost** [comment]
@Glease 
...
RFtools 200多行? 我汉化的是1.9.4 branch下的[en_US.lang](https://github.com/McJty/RFTools/blob/1.9.4/src/main/resources/assets/rftools/lang/en_US.lang)
至于Deep Resonance也是只更新了一样东西, 不过这里还修改了不少条目.

**Comment by Glease** [comment]
@3TUSK
 Well, I'd love to help, 但我高三，快高考了，虽然没有大问题但是父母很关心，没办法花大量的时间去翻译，也就能聊聊天看看小说(我甚至停掉了开发)，所以…… Sorry for that. 也许考完可以来帮帮忙，暂时是不行了。

@partial-s
IIRC, rftools and deepresonance both have its own translation. rftools's need an minor update of one single entry, but your patch lacks more than additions. (the latest official zh_CN.lang for rftools has 200+ lines, but yours has only ~150 lines) ~~Meanwhile, deepresonance has everything ready. nothing really needs changes.~~ My fault, I missed a line. Looks good. (~~both of~~ above ~~two~~thing happens months ago!) There must be something wrong. Did you referenced some ancient en_US.lang files?

> Something wrong with my network, I can neither modify nor delete my comments. @3TUSK could you please help me remove it?

--- Original Message ---

**Comment by Glease** [comment]
Well, 我读的是189的分支……my fault...... so ign

--- Original Message ---

**Comment by ghost** [comment]
@Glease 
嗯... #65 是个汉化 BTM16.2 里面mod的策划, 版本都是1.9的... 另外你上面发重复了

**Comment by GWYOG** [comment]
@partial-s  @Glease  嗯..我来说明一下RFTools汉化行数的事情吧，你们如果知道的话就无视我就好了....事情是这样的，去年大概11月的时候@Glease把1.7.10的RFTools汉化完成了，有两百多行。但RFTools到mc1.8+后分成了两个部分，一部分是RFTools的基础部分，还叫RFTools；另一部分是原来RFTools的维度部分，变成了新mod RFTools Dimensions。今年寒假的时候我把原来@Glease的汉化分了开来并稍作修改提交给McJty了，所以现在的RFTools才会只有一百来行....至于RFTools Dimensions， @partial-s 你能也一道更新一下文本吗？刚看了一下似乎只多了一行

**Comment by ghost** [comment]
@GWYOG 难怪现在RFtools的文本少了那么多... 话说RFToolsDimensions不在BTM16计划内, 所以汉化就交给你了【甩锅

**Comment by GWYOG** [comment]
@partial-s  #(喷) 最近我有点忙，汉化的事都放在一边了，等有空的时候我再去更新一下文本吧....(顺道还要更新下参加BTM16 2.0的EIOA和ExtraFood)

**Comment by 3TUSK** [comment]
甩这么多锅不如再call几个人过来...我不会告诉你我现在就在期末考试... so sad.

**Comment by 3TUSK** [comment]
但是我觉得RFTools Dimension应该会去BTM 16.2...

**Comment by ghost** [comment]
到时候直接提交到作者那边吧

**Comment by 3TUSK** [comment]
Will do.

**Comment by 3TUSK** [comment]
@bakaxyf 再等几天...若是6月1号没有新问题的话就可以merge了。 I will let you handle this.

**Comment by 3TUSK** [comment]
> 谁来个可以的表情图

**Comment by GWYOG** [comment]
2dbf83025db81cb5

**Pull request merged**
